_target_: agents.encoders.multi_image_obs_encoder.MultiImageObsEncoder
_partial_: True
embed_dim: ${..embed_dim}

# Arguments passed at runtime:
# dataset: ???

rgb_model:
  _target_: agents.encoders.resnets.beso_resnet_encoder
  _partial_: True
  embed_dim: ${..embed_dim}
  pretrained_weights: null

resize_shape: null
crop_shape: null
random_crop: False
share_rgb_model: False
imagenet_norm: True
