_target_: agents.bc_agent.BC_Agent
_recursive_: false

defaults:
  - model: bc/bc_transformer
#  - model: bc/bc_xlstm
  - obs_encoders: resnet
#  language_encoders:

optimization:
  _target_: torch.optim.Adam
  lr: 5e-4
  weight_decay: 0

action_seq_size: ${act_seq_len}

if_robot_states: False
if_film_condition: False
device: ${device}
state_dim: ${obs_dim}
latent_dim: ${latent_dim}
