# @package _global_

defaults:
  - /transforms@data.preprocess.t10_resize: image_resize

  - /transforms@data.preprocess.t15_to_pointmap: to_pointmap

  # # Collect statistics to scale pointmaps to [-1, 1]^3
  # # Do this after translations/cropping and before masking/jittering
  # - /transforms@data.preprocess.t30_pointmap_normalize: pointmap_normalize

  - /transforms@data.preprocess.t99_cleanup: cleanup

  # apply jitter data augmentation
  - /transforms@data.gpu_batch_transforms.t10_jitter: jitter

data:
  preprocess:
    # we save the preprocessed data to a unique path so as not to overwrite other obs modalities
    root_dir: ${paths.preprocessed_dir}/${data.task_suite}/${data.name}_pointmaps

    t10_resize:
      shape: 128  # rescale streams from 256x256 to 128x128

    t15_to_pointmap:
      color: False
      max_depth: null  # disabled because we don't know the effect of setting points far away to zero depth

    t99_cleanup:
      keep_stream_types: pointmap  # only keep pointmap streams

  gpu_batch_transforms:
    t10_jitter:
      sigma: 0.005

# metadata
modality: pointmap
