# @package _global_

defaults:
  - /transforms@data.preprocess.t10_resize: image_resize

  - /transforms@data.preprocess.t15_to_pcd: to_pointcloud
  
  - /transforms@data.preprocess.t20_crop_pcd: pointcloud_crop_maniskill

  # # disable random transforms for now
  # - /transforms@data.preprocess.t7_random_transform: pointcloud_random_transform

  - /transforms@data.preprocess.t99_cleanup: cleanup

  - /transforms@data.gpu_batch_transforms.t2_sample_voxel: pointcloud_downsample_voxel

  # apply jitter data augmentation
  - /transforms@data.gpu_batch_transforms.t10_jitter: jitter
  
  # we don't need to normalize the pointclouds because they are already sort of
  # within the range [0, 1] after cropping
  # - /transforms@data.gpu_batch_transforms.t5_normalize: pointcloud_normalize

data:
  # Below is just the default configuration copied here for convenience. Change as needed.
  preprocess:
    # we save the preprocessed data to a unique path so as not to overwrite other obs modalities
    root_dir: ${paths.preprocessed_dir}/maniskill/${data.name}_pointclouds

    t10_resize:
      shape: 128  # scale shortest side to 128 and keep aspect ratio

    t15_to_pcd:
      color: False
      max_depth: 2.0  # in meters
      warn_min_points: 100

    t99_cleanup:
      keep_stream_types: []  # keep no stream types, i.e. remove all
      drop_keys: [base_cam_transform, gripper_cam_transform]

  gpu_batch_transforms:
    t2_sample_voxel:
      size: 0.006

    t10_jitter:
      sigma: 0.002

# disable the batch size finder for point clouds, because the data points 
# don't have a consistent memory size
callbacks:
  batch_size_finder: null
