# @package _global_

defaults:
  - /transforms@data.preprocess.t15_to_pcd: to_pointcloud

  - /transforms@data.preprocess.t99_cleanup: cleanup

  - /transforms@data.gpu_batch_transforms.t2_sample_voxel: pointcloud_downsample_voxel

  # apply jitter data augmentation
  - /transforms@data.gpu_batch_transforms.t10_jitter: jitter

data:
  preprocess:
    # we save the preprocessed data to a unique path so as not to overwrite other obs modalities
    root_dir: ${paths.preprocessed_dir}/${data.task_suite}/${data.name}_pointclouds

    # point clouds begin with (approx.) 128*128*2 = 32768 points
    t15_to_pcd:
      color: True
      max_depth: 2.0  # in meters
      warn_min_points: 100

    t19_center_pcd:
      _target_: transforms.pointcloud_center.CenterPointCloudTrajectory
      _partial_: True
      transform_obs_key: fetch_head_transform
      xy_only: True

    # after cropping approx. 15000-30000 points
    t20_crop_pcd:
      _target_: transforms.pointcloud_crop.CropPointCloud
      _partial_: True
      x_range: [-2.0, 2.0]
      y_range: [-2.0, 2.0]
      z_range: [0.05, 2.0]
      warn_min_points: 100

    t99_cleanup:
      keep_stream_types: []  # keep no stream types, i.e. remove all

  gpu_batch_transforms:
    # after downsampling approx. 5000-12000 points
    t2_sample_voxel:
      size: 0.01

    t10_jitter:
      sigma: 0.005

# disable the batch size finder for point clouds, because the data points 
# don't have a consistent memory size
callbacks:
  batch_size_finder: null

# metadata
modality: pointcloud
