# @package _global_

defaults:
  # Larger vision tasks
  - /transforms@data.preprepreprocess.t00_remove_unused_cams: cleanup
  # - /goals@data.preprepreprocess.t01_target_tool_from_foldername: add_target_tool_from_foldername_real
  - /transforms@data.preprepreprocess.t02_samv3: pointed_samv3
  # - /transforms@data.preprepreprocess.t02_samv3: grounding_samv3_segmenter
  - /transforms@data.preprepreprocess.t03_dinov3: dinov3
  - /transforms@data.preprepreprocess.t04_cotracker: cotracker_single
  - /transforms@data.preprepreprocess.t05_target_to_featured_pointcloud: to_masked_featured_pointcloud
  - /transforms@data.preprepreprocess.t06_tool_to_featured_pointcloud: to_tracked_featured_pointcloud
  - /transforms@data.preprepreprocess.t99_cleanup: cleanup

  # Last little part that connects everyting
  - /transforms@data.prepreprocess.t02_ee_pose_to_five_points: absolute_ee_pose_to_five_points
  - /transforms@data.prepreprocess.t03_to_sliding_window_action: to_sliding_window_action
  - /transforms@data.prepreprocess.t99_cleanup: cleanup

  - /transforms@data.preprocess.t00_no_op: noop

  - /transforms@data.gpu_batch_transforms.t01_fps_prep: nested_pointcloud_prep_downsample_fps
  - /transforms@data.gpu_batch_transforms.t02_to_pakt_action_obs: to_pakt_action_obs
  - /transforms@data.gpu_batch_transforms.t03_pakt_localizer: pakt_localizer
  - /transforms@data.gpu_batch_transforms.t04_random_rotation: pakt_random_rotation

  # - /transforms@data.gpu_batch_transforms.t99_render_pcd: pakt_render_pointcloud


camera_keys: ["front_left_cam", "front_right_cam"]
rgb_key: left

data:
  # Below is just the default configuration copied here for convenience. Change as needed.
  preprepreprocess:
    backend: hdf5
    # we save the preprocessed data to a unique path so as not to overwrite other obs modalities
    root_dir: ${paths.preprepreprocessed_dir}/real/${data.name}_pointclouds
    overwrite: True
    
    t00_remove_unused_cams:
      drop_keys: [gripper_cam]
      drop_streams: [front_left_cam/right, front_right_cam/right]

    t99_cleanup:
      keep_stream_types: []  # keep no stream types, i.e. remove all
      drop_keys: [left_cam, right_cam, gripper_cam]

  prepreprocess:
    backend: hdf5
    # we save the preprocessed data to a unique path so as not to overwrite other obs modalities
    root_dir: ${paths.preprocessed_dir}/real/${data.name}_pointclouds
    overwrite: True

    t01_action_type:
      _target_: transforms.action_switch_type.SwitchActionType
      _partial_: True
      obs_key: next_target_ee_pose

    t02_ee_pose_to_five_points:
      apply_base_pose: False 
      quat_action: True

    t99_cleanup:
      keep_stream_types: []  # keep no stream types, i.e. remove all
      drop_keys: [left_cam_pose, right_cam_pose, gripper_cam_pose, front_left_cam, front_right_cam, gripper_cam]
  
  preprocess:
    backend: pakt_hdf5
    # we save the preprocessed data to a unique path so as not to overwrite other obs modalities
    root_dir: ${paths.preprocessed_dir}/real/${data.name}_pointclouds
    overwrite: True

# disable the batch size finder for point clouds, because the data points 
# don't have a consistent memory size
callbacks:
  batch_size_finder: null

# metadata
modality: pointcloud
