# @package _global_

defaults:
  - /transforms@data.prepreprocess.t0_drop_depth: cleanup

  # replace measured depth with FoundationStereo depth
  - /transforms@data.prepreprocess.t3_foundationstereo: foundation_stereo

  # remove streams we don't need to reduce datasize and compute
  # TODO: verify that multiple cleanup transforms don't overwrite each other in env transforms
  - /transforms@data.prepreprocess.t4_cleanup_stereo: cleanup

  - /transforms@data.prepreprocess.t5_resize: image_resize

  - /transforms@data.prepreprocess.t6_crop_image: image_centercrop

data:
  prepreprocess:
    backend: hdf5
    root_dir: ${append_to_stem:${data.dataset.root_dir},_fs_224x224}

    t0_drop_depth:
      drop_stream_types: depth

    t4_cleanup_stereo:
      drop_stream_types: ir  # drop IR streams from the realsense
      drop_stream_names: right  # drop right rgb stream from the zeds

    t5_resize:
      shape: 224  # scale shortest side to 224 and keep aspect ratio

    t6_crop_image:
      shape: 224  # crop all streams to 224x224
