# @package _global_

defaults:
  - real_track
  # Make the "target" step tracked (instead of masked)
  - override /transforms@data.preprepreprocess.t04_cotracker: cotracker_both
  - override /transforms@data.preprepreprocess.t05_target_to_featured_pointcloud: to_tracked_featured_pointcloud
  - _self_

data:
  preprepreprocess:
    t05_target_to_featured_pointcloud:
      track_key: target_cotracker_tracks
      visibility_key: target_cotracker_visibility
      out_key: target_points

  gpu_batch_transforms:
    t02_to_pakt_action_obs:
      tracked_points_keys: [tool_points, target_points]
      untracked_points_keys: []
    t03_pakt_localizer:
      localization_target: target_points