# @package _global_

defaults:
  - /transforms@data.preprocess.t0_cleanup: cleanup

  - /transforms@data.preprocess.t1_triangle_crop: triangle_crop_224x224

  - /transforms@data.preprocess.t9_norm_depth: depth_normalize

  - /transforms@data.gpu_batch_transforms.t90_depth_jitter: translational_jitter

data:
  preprocess:
    root_dir: ${paths.preprocessed_dir}/real/${data.name}_depth

    t0_cleanup:
      keep_stream_types: depth
      drop_keys: gripper_cam_transform
