# @package _global_

defaults:
  - rgbd_imagenet
  # replace measured depth with FoundationStereo depth
  - /transforms@data.preprocess_transforms.t1-2_foundationstereo: foundation_stereo
  - _self_

data:
  # Below is just the default configuration copied here for convenience. Change as needed.
  preprocess_transforms:
    t1-2_foundationstereo:
      engine_path: ${paths.root_dir}/foundation_stereo_models/foundation_stereo_large_3x480x640.plan
