# @package _global_

defaults:
  # pretrained resnet18 expects images resized to 256x256...
  - /transforms@data.preprocess_transforms.t1_resize: image_resize

  # ...and then cropped to 224x224
  - /transforms@data.preprocess_transforms.t2_crop: image_centercrop

  # convert to pointmap
  - /transforms@data.preprocess_transforms.t3_to_pointmap: to_pointmap
