# @package _global_

defaults:
  - /transforms@data.preprocess_transforms.t2_resize: image_resize

  # pretrained resnet18 expects images of shape 224x224
  - /transforms@data.preprocess_transforms.t3_crop_image: image_centercrop
  
  # apply ImageNet normalization
  - /transforms@data.gpu_batch_transforms.t4_norm_image: imagenet_norm

data:
  # Below is just the default configuration copied here for convenience. Change as needed.
  preprocess_transforms:
    t2_resize:
      shape: 224  # scale shortest side to 224 and keep aspect ratio
    
    t3_crop_image:
      shape: 224  # crop to 224x224 square

  # we save the preprocessed data to a unique path so as not to overwrite other obs modalities
  dataset:
    preprocessed_dir: ${paths.preprocessed_dir}/${data.name}/multiview_image
