# @package _global_

defaults:

  # Remove unused defaults and get the actual segmentations from robocasa
  - /transforms@data.preprepreprocess.t01_remove_inhand: cleanup
  - /transforms@data.preprepreprocess.t02_apply_robocasa_segmentations: apply_robocasa_segmentations
  
  # Larger vision tasks
  - /transforms@data.prepreprocess.t03_dinov3: dinov3
  - /transforms@data.prepreprocess.t04_cotracker: cotracker
  - /transforms@data.prepreprocess.t05_to_masked_featured_pointcloud: to_masked_featured_pointcloud
  - /transforms@data.prepreprocess.t06_to_tracked_featured_pointcloud: to_tracked_featured_pointcloud
  - /transforms@data.prepreprocess.t99_cleanup: cleanup

  # Last little part that connects everyting
  - /transforms@data.preprocess.t01_robocasa_use_abs_actions: robocasa_use_abs_actions
  - /transforms@data.preprocess.t02_ee_pose_to_five_points: absolute_ee_pose_to_five_points
  - /transforms@data.preprocess.t07_to_pakt_action_obs: to_pakt_action_obs
  - /transforms@data.preprocess.t08_pakt_localizer: pakt_localizer
  - /transforms@data.preprocess.t99_cleanup: cleanup



data:
  preprepreprocess:
    backend: hdf5
    root_dir: ${paths.preprepreprocessed_dir}/robocasa/${data.name}
    t01_remove_inhand:
      drop_keys: [gripper_cam]

  # Below is just the default configuration copied here for convenience. Change as needed.
  prepreprocess:
    backend: hdf5
    # we save the preprocessed data to a unique path so as not to overwrite other obs modalities
    root_dir: ${paths.prepreprocessed_dir}/robocasa/${data.name}_pointclouds
    overwrite: True
    t99_cleanup:
      keep_stream_types: []  # keep no stream types, i.e. remove all
      drop_keys: [left_cam_pose, right_cam_pose, gripper_cam_pose, left_cam, right_cam, gripper_cam]

  preprocess:
    backend: pakt_hdf5
    # we save the preprocessed data to a unique path so as not to overwrite other obs modalities
    root_dir: ${paths.preprocessed_dir}/robocasa/${data.name}_pointclouds
    overwrite: True

    t99_cleanup:
      keep_stream_types: []  # keep no stream types, i.e. remove all
      drop_keys: [left_cam_pose, right_cam_pose, gripper_cam_pose, left_cam, right_cam, gripper_cam]

# disable the batch size finder for point clouds, because the data points 
# don't have a consistent memory size
callbacks:
  batch_size_finder: null

# metadata
modality: pointcloud
