# @package _global_

defaults:
  - /transforms@data.preprocess.t99_cleanup: cleanup

  # apply ImageNet normalization
  - /transforms@data.gpu_batch_transforms.t99_norm_image: imagenet_norm

data:
  preprocess:
    # we save the preprocessed data to a unique path so as not to overwrite other obs modalities
    root_dir: ${paths.preprocessed_dir}/robocasa/${data.name}_rgb

    t99_cleanup:
      keep_stream_types: rgb  # only keep rgb streams
      drop_keys: [left_cam_pose, right_cam_pose, gripper_cam_pose]

# metadata
modality: rgb
