# @package _global_

defaults:
  - /transforms@data.preprocess_transforms.t3_to_pcd: to_pointcloud

  # we can't really crop because of the random world frame, but the cameras don't see any faraway points anyway  

  # no need to apply random transform for robocasa, since this is in the dataset already

  - /transforms@data.preprocess_transforms.t99_cleanup: cleanup

  - /transforms@data.gpu_batch_transforms.t1_voxel_downsample: pointcloud_downsample_voxel

  # apply jitter data augmentation
  - /transforms@data.gpu_batch_transforms.t2_jitter: pointcloud_jitter
  
  # we don't need to normalize the pointclouds because they are already sort of
  # within the range [0, 1] after cropping
  # - /transforms@data.gpu_batch_transforms.t5_normalize: pointcloud_normalize

data:
  # Below is just the default configuration copied here for convenience. Change as needed.
  preprocess_transforms:
    t3_to_pcd:
      color: False
      max_depth: 5.0  # in meters
      warn_min_points: 100

    t99_cleanup:
      keep_stream_types: []  # keep no stream types, i.e. remove all
      drop_keys: gripper_cam_transform

  gpu_batch_transforms:
    t1_voxel_downsample:
      size: 0.01

    t2_jitter:
      max_sigma: 0.002  # slightly higher jitter for robocasa
  
  dataset:
    preprocessed_dir: ${paths.preprocessed_dir}/${data.name}/pointclouds

# disable the batch size finder for point clouds, because the data points 
# don't have a consistent memory size
callbacks:
  batch_size_finder: null
