# @package _global_

defaults:
  # apply ImageNet normalization in preprocessing, because color channels will be added to pointmap
  - /transforms@data.preprocess.t4-9_norm_image: imagenet_norm

  # convert to pointmap
  - /transforms@data.preprocess.t5_to_pointmap: to_pointmap

  - /transforms@data.preprocess.t9_cleanup: cleanup

data:
  preprocess:
    t5_to_pointmap:
      color: True

    t9_cleanup:
      keep_stream_types: [pointmap]  # color data is stored inside pointmap
      drop_keys: gripper_cam_transform

  # we save the preprocessed data to a unique path so as not to overwrite other obs modalities
  dataset:
    preprocessed_dir: ${paths.preprocessed_dir}/${data.name}/multiview_pointmap_6ch
