# @package _global_

defaults:
  # convert to pointmap
  - /transforms@data.preprocess_transforms.t5-1_to_pointmap: to_pointmap

  - /transforms@data.preprocess_transforms.t5-2_crop_pointmap: pointmap_crop_sim

  - /transforms@data.preprocess_transforms.t6-1_random_transform: pointmap_random_transform

  # Collect statistics to scale pointmaps to [-1, 1]^3
  # Do this after translations/cropping and before masking/jittering
  - /transforms@data.preprocess_transforms.t6-2_pointmap_normalize: pointmap_normalize

  - /transforms@data.preprocess_transforms.t99_cleanup: cleanup

  # apply jitter data augmentation
  - /transforms@data.gpu_batch_transforms.t2_jitter: translational_jitter

  # apply ImageNet normalization
  - /transforms@data.gpu_batch_transforms.t99_norm_image: imagenet_norm

data:
  preprocess_transforms:
    t5-1_to_pointmap:
      color: False  # to use 6-channel fusion, use sim_pointmaps_6ch config
      max_depth: null # in meters

    t6-1_pointmap_random_transform:
      max_angle: 20 # in degrees
      max_translation: [0.25, 0.25, 0.25] # in meters

    t99_cleanup:
      # keep rgb streams if MultiviewPointMapTokenizer fusion type is not None (or can't be resolved)
      keep_stream_types: ${if:${oc.select:agent.obs_encoder.t10_image_tokenizer.fusion_type,True},[pointmap,rgb],[pointmap]}
      drop_stream_names: right  # even if we keep rgb streams, drop the right rgb stream
      drop_keys: gripper_cam_transform

  gpu_batch_transforms:
    t2_jitter:
      max_sigma: 0.002

  # we save the preprocessed data to a unique path so as not to overwrite other obs modalities
  dataset:
    preprocessed_dir: ${paths.preprocessed_dir}/${data.name}/multiview_pointmap
