# @package _global_

# Done
data:
  preprepreprocess:
    # convert absolute joint actions to delta joint action
    t00_apply_robocasa_segmentations:
      _target_: transforms.robocasa_segmentations.ApplyRobocasaSegmentations
      _partial_: True

      camera_keys: ${camera_keys}
      segmentation_keys: [microwave]
      mask_out_keys: [tool_segmentation]
