# @package _global_

# Used by most robocasa pnp environments, exceptions are counter_to_sink, counter_to_cab, cab_to_counter
# Done
data:
  prepreprocess:
    # convert absolute joint actions to delta joint action
    t00_apply_robocasa_segmentations:
      _target_: transforms.robocasa_segmentations.ApplyRobocasaSegmentations
      _partial_: True

      camera_keys: ${camera_keys}
      segmentation_keys: [obj, container]
      mask_out_keys: [tool_segmentation, target_segmentation]
