name: adamw
_target_: torch.optim.AdamW
_partial_: True
_convert_: all  # convert ListConfig (e.g. the betas argument) to python list so it can be unpickled by torch
lr: 1e-4
betas: [0.9, 0.9]
weight_decay: 0.05
