python run.py  --config-name=libero_horeka_config \
            --multirun agents=bc_agent \
            agent_name=bc_mamba \
            group=bc_decoder_only \
            agents/model=bc/bc_dec_mamba \
            task_suite=libero_object \
            mamba_n_layer_encoder=16 \
            mamba_encoder_cfg.d_state=16 \
            seed=0,1,2