python run.py  --config-name=libero_horeka_config \
            --multirun agents=bc_agent \
            agent_name=bc_transformer \
            group=bc_decoder_only_old_optimizer \
            agents/model=bc/bc_dec_transformer \
            task_suite=libero_goal,libero_spatial \
            traj_per_task=10 \
            agents.optimization.lr=1e-4,1e-5 \
            seed=0,1,2