_target_: models.transformer.TransformerEncoder
_partial_: True
embed_dim: ${..token_dim}
n_layers: 4
layer_module:
  _target_: models.transformer.TransformerEncoderLayer
  _partial_: True
  norm_first: True
  norm_module:
    _target_: torch.nn.RMSNorm
    _partial_: True
    eps: 1e-6
  attention_module:
    _target_: models.attention.MultiHeadSelfAttention
    _partial_: True
    n_heads: 4
    dropout: 0.3
    is_causal: False
    bias: False
    qk_norm_module:
      _target_: torch.nn.RMSNorm
      _partial_: True
      eps: 1e-6
  residual_dropout_module:
    _target_: torch.nn.Dropout
    _partial_: True
    p: 0.1
  mlp1_module:
    _target_: models.transformer.SwishGLU
    _partial_: True
  activation:
    _target_: torch.nn.Identity
    _partial_: True
  # mlp1_module:
  #   _target_: torch.nn.Linear
  #   _partial_: True
  # activation:
  #   _target_: torch.nn.ReLU
  #   _partial_: True
  mlp_dropout_module:
    _target_: torch.nn.Dropout
    _partial_: True
    p: 0.1
  mlp2_module:
    _target_: torch.nn.Linear
    _partial_: True
    bias: False
norm_module:
  _target_: torch.nn.RMSNorm
  _partial_: True
  eps: 1e-6
