name: Gaussian RFFs + SPE
_target_: models.fourier_features.RandomFourierFeatures
_partial_: True  # requires input_dim
sigma: 10.0
n_wavelengths: 16
axis_aligned: False
learn: False
linear_transform: True
components: sincos
cat_input_to_out: False
