name: FourierFeatures
_target_: models.pos_encoder.FourierFeatures
_partial_: True  # requires input_dim
n_wavelengths: 6
max_wavelength: 2.0
min_wavelength: null
interval: 0.5
learnable: True
cat_input_to_out: True
