name: FourierFeatures
_target_: models.fourier_features.FourierFeatures
_partial_: True  # requires input_dim
n_wavelengths: 16
max_wavelength: 0.5
min_wavelength: 0.01
learn: False
linear_transform: False
components: sin
cat_input_to_out: True
