_target_: agents.models.flow_matching.rf.RF
_recursive_: false

ln: False
device: ${device}

backbones:
  _target_: agents.backbones.decoder_only.Noise_Dec_only
  _recursive_: false
  state_dim: ${latent_dim}
  action_dim: ${action_dim}
  goal_dim: ${goal_dim}
  goal_conditioned: ${goal_conditioned}
  goal_seq_len: 1
  obs_seq_len: ${obs_tokens}
  action_seq_len: ${act_seq_len}
  embed_pdrob: 0
  # Architecture details
  embed_dim: ${n_embd}
  device: ${device}
  linear_output: true

  use_ada_conditioning: False
  diffusion_type: 'rf'

  encoder:
    _target_: agents.backbones.xlstm.xlstm.xlstmEncoder
    xlstm_config:
      mlstm_block:
        mlstm:
          conv1d_kernel_size: 4
          qkv_proj_blocksize: 8
          num_heads: 8
          proj_factor: 2.0
          dropout: 0.0
      slstm_block:
        enabled: false
        slstm:
          backend: "cuda"
          num_heads: 4
          conv1d_kernel_size: 4
          bias_init: "powerlaw_blockdependent"
        feedforward:
          proj_factor: 1.3
          act_fn: "gelu"
      context_length: 0 #edit in xlstm.py
      num_blocks: ${xlstm_encoder_blocks}
      embedding_dim: ${n_embd}  # Using the same embedding dimension
      add_post_blocks_norm: true
      bias: false
      dropout: 0.0
      slstm_at: [ 1 ]
    embed_dim: ${n_embd}
    bias: false
    block_size: 14