defaults:
  - /models/conv@image_encoder: resnet

name: multiview_image_tokenizer
_target_: transforms.multiview_image_tokenizer.MultiviewImageTokenizer
_partial_: True
embed_dim: ${..embed_dim}
shared_encoder: False
