defaults:
  - /models/pos_encoder@token_pos_encoder: point_mae
  - /models/pos_projection@spatial_encoder: null

name: pointpatch_tokenizer
_target_: transforms.pointpatchrl_tokenizer.PointPatchTokenizer
_partial_: True

embed_dim: ${..embed_dim}
mlp_1:
  _target_: models.mlp.MlpModel
  _partial_: True  # requires in_features
  hidden_sizes: [128]
  out_features: 256
  activation: ReLU
mlp_2:
  _target_: models.mlp.MlpModel
  _partial_: True  # requires out_features
  _args_: ["${prod:2,${...mlp_1.out_features}}"]  # in_features must be 2 * out_features of mlp_1
  hidden_sizes: [512]
  activation: ReLU
