defaults:
  - /models/vision_encoder@image_encoder: resnet
  - /models/vision_encoder@pointmap_encoder: resnet

name: multiview_pointmap_tokenizer
_target_: transforms.multiview_pointmap_tokenizer.MultiviewPointMapTokenizer
_partial_: True
embed_dim: ${..embed_dim}
fusion_type: cat
