name: ee pose tokenizer
_target_: transforms.robot_state_tokenizer.RobotStateEncoder
_partial_: True
obs_key: [ee_pose, gripper_width]
model:
  _target_: models.mlp.MlpModel
  _partial_: True  # requires in_features
  hidden_sizes: [256]
  activation: GELU
embed_dim: ${..embed_dim}
token_pos_encoder:
  _target_: torch.nn.Embedding
  _partial_: True  # requires num_embeddings and embedding_dim
