# @package _global_

defaults:
  # tokenize the depth map using ConvNeXtv2
  - /tokenizers@agent.obs_encoder.t10_image_tokenizer: conv_tokenizer

  - override /models/vision_encoder@agent.obs_encoder.t10_image_tokenizer.encoder: timm_convnextv2

agent:
  obs_encoder:
    embed_dim: 256

    t10_image_tokenizer:
      image_type: depth
      shared_encoder: False

logger:
  wandb:
    tags: ["depth", "convnextv2"]
