# @package _global_

defaults:
  # tokenize the rgb images using a ResNet
  - /tokenizers@agent.obs_encoder.t10_image_tokenizer: image_tokenizer

  - override /models/vision_encoder@agent.obs_encoder.t10_image_tokenizer.image_encoder: timm_convnextv2

agent:
  obs_encoder:
    embed_dim: 256
    t10_image_tokenizer:
      shared_encoder: True
      image_type: depth

logger:
  wandb:
    tags: ["depth", "convnextv2"]