# @package _global_

defaults:
  # tokenize the rgb images using a ResNet
  - /tokenizers@agent.obs_encoder.t10_resnets: image_tokenizer

agent:
  obs_encoder:
    embed_dim: 256
    
    t10_resnets:
      shared_encoder: False
      image_type: depth

logger:
  wandb:
    tags: ["depth", "resnet18"]
