# @package _global_

defaults:
  # tokenize the rgb images using a ResNet
  - /tokenizers@agent.obs_encoder.t10_resnets: resnet_image_tokenizer
  # add tokens for the robot state
  - /tokenizers@agent.obs_encoder.t20_robot_state: linear_robot_state_tokenizer

agent:
  obs_encoder:
    embed_dim: 256
    
    t10_resnets:
      shared_encoder: False
      image_type: depth
    
      image_encoder:
        # resnet18
        input_channels: 1

logger:
  wandb:
    tags: ["depth", "resnet18"]
