# @package _global_

defaults:
  # # FPS sampling seems to hurt performance (at least on RoboCasa)
  # - /transforms@data.gpu_batch_transforms.t9_sample_fps: pointcloud_downsample_fps

  - /tokenizers@agent.obs_encoder.t10_tokenizer: dp3_tokenizer
  - /models/spatial_encoder@agent.obs_encoder.t10_tokenizer.spatial_encoder: fourier_features
  
# Below is just the default configuration copied here for convenience. Change as needed.
agent:
  obs_encoder:
    embed_dim: 256
    t10_tokenizer:
      mlp_1:
        hidden_sizes: [64, 128]
        out_features: 256
        activation: ReLU
        norm: LayerNorm

data:
  gpu_batch_transforms:
    t9_sample_fps:
      n_points: 2048  # original uses 1024

  batch_size: ${floor_div:${platform.batch_size},8}  # 1/8 of typical batch size

logger:
  wandb:
    tags: ["pointcloud", "dp3"]

# metadata
encoder: DP3
has_fourier: True
