# @package _global_

defaults:
  - /tokenizers@agent.obs_encoder.t10_tokenizer: dp3_tokenizer
  - /models/spatial_encoder@agent.obs_encoder.t10_tokenizer.spatial_encoder: fourier_features

  # apply ImageNet normalization
  - /transforms@data.gpu_batch_transforms.t99_norm_image: imagenet_norm

  # RGB image tokenizer
  - /tokenizers@agent.obs_encoder.t10_image_tokenizer: image_tokenizer
  - override /models/vision_encoder@agent.obs_encoder.t10_image_tokenizer.image_encoder: timm_convnextv2


# Below is just the default configuration copied here for convenience. Change as needed.
agent:
  obs_encoder:
    embed_dim: 256

    t10_image_tokenizer:
      shared_encoder: False
      image_type: rgb
      image_encoder:
        pretrained: False

    t10_tokenizer:
      mlp_1:
        hidden_sizes: [64, 128]
        out_features: 256
        activation: ReLU
        norm: LayerNorm
      spatial_encoder:
        n_wavelengths: 8
        max_wavelength: 4.0
        min_wavelength: 0.06
        cat_cartesian_coordinates: False

data:
  batch_size: ${floor_div:${platform.batch_size},4}  # 1/4 of typical batch size

  preprocess_transforms:
    t9_cleanup:
      keep_stream_types: [rgb]  # keep rgb streams
      drop_stream_names: [right]  # but drop any right rgb streams if they exist

logger:
  wandb:
    tags: ["rgb+pointcloud", "dp3", "convnextv2"]
