# @package _global_

# defaults:
  # pointpatchrl tokenizer for pointclouds
  # - /tokenizers@agent.obs_encoder.t11_tokenizer: pakt_tokenizer

# agent:
#   obs_encoder:
#     embed_dim: 256

data:
  batch_size: ${platform.batch_size}  # 1/2 of typical batch size

logger:
  wandb:
    tags: []

# metadata
encoder: PointPatch+ConvNeXtV2
has_fourier: True
