# @package _global_

defaults:
  - /tokenizers@agent.obs_encoder.t10_tokenizer: pcm_tokenizer
  - /models/spatial_encoder@agent.obs_encoder.t10_tokenizer.spatial_encoder: fourier_features

agent:
  obs_encoder:
    embed_dim: 256
    t10_tokenizer:
      n_patches: 2048
      patch_size: 16


data:
  batch_size: ${floor_div:${platform.batch_size},4}  # 1/4 of typical batch size

logger:
  wandb:
    tags: ["pointcloud", "pcm_pointnet"]

# metadata
encoder: PCM PointNet
has_fourier: True
