# @package _global_

defaults:
  - /models/spatial_encoder@agent.obs_encoder.t10_tokenizer.spatial_encoder: fourier_features
  
# Below is just the default configuration copied here for convenience. Change as needed.
agent:
  obs_encoder:
    embed_dim: 256
    t10_tokenizer:
      name: pointtransformer_tokenizer
      _target_: transforms.pointtransformer_tokenizer.PointTransformerTokenizer
      _partial_: True
      embed_dim: ${..embed_dim}
      hidden_sizes: [32, 64, 128, 256, 512]
      k: 16
      token_pos_encoder:
        _target_: torch.nn.Embedding
        _partial_: True  # requires num_embeddings and embedding_dim

data:
  batch_size: ${floor_div:${platform.batch_size},16}  # 1/16 of typical batch size

logger:
  wandb:
    tags: ["pointcloud", "pointtransformer"]

# metadata
encoder: PointTransformer
has_fourier: True
