# @package _global_

defaults:
  # tokenize the pointmaps using a ResNet
  - /tokenizers@agent.obs_encoder.t10_image_tokenizer: pointmap_tokenizer
  - override /models/vision_encoder@agent.obs_encoder.t10_image_tokenizer.image_encoder: timm_resnet18
  - override /models/vision_encoder@agent.obs_encoder.t10_image_tokenizer.pointmap_encoder: timm_resnet18

# Below is just the default configuration copied here for convenience. Change as needed.
agent:
  obs_encoder:
    embed_dim: 256
    
    t10_image_tokenizer:
      shared_encoder: False
      fusion_type: null  # Literal["6ch", "add", "cat"] | null
      image_encoder:
        pretrained: True

logger:
  wandb:
    tags: ["pointmap", "timm_resnet18"]
