# @package _global_

defaults:
  # tokenize the pointmaps using a ResNet
  - /tokenizers@agent.obs_encoder.t10_image_tokenizer: pointmap_tokenizer

# Below is just the default configuration copied here for convenience. Change as needed.
agent:
  obs_encoder:
    embed_dim: 256
    
    t10_image_tokenizer:
      shared_encoder: False
      fusion_type: cat  # Literal["6ch", "add", "cat"] | None
      image_encoder:
        # resnet18
        pretrained_weights: IMAGENET1K_V1  # null or "IMAGENET1K_V1"
        freeze_backbone: False

data:
  batch_size: ${floor_div:${platform.batch_size},2}  # 1/2 of typical batch size

logger:
  wandb:
    tags: ["pointmap", "resnet18"]
