# @package _global_

defaults:
  # tokenize the images using pretrained ConvNeXtv2
  - /tokenizers@agent.obs_encoder.t10_image_tokenizer: conv_tokenizer

  - override /models/vision_encoder@agent.obs_encoder.t10_image_tokenizer.encoder: timm_convnextv2

  # increase size of transformer according to what David uses
  - override /agent/noise_model/backbone@agent.noise_model.decoder: transformer_large

agent:
  obs_encoder:
    embed_dim: 256

    t10_image_tokenizer:
      image_type: rgb
      encoder:
        pretrained: True
      shared_encoder: False

logger:
  wandb:
    tags: ["rgb", "convnextv2"]

# metadata
encoder: ConvNeXtV2
has_fourier: False
