# @package _global_

defaults:
  # tokenize the pointmaps using pretrained ConvNeXt
  - /tokenizers@agent.obs_encoder.t10_image_tokenizer: image_tokenizer

  - override /models/vision_encoder@agent.obs_encoder.t10_image_tokenizer.image_encoder: timm_convnextv2

# Below is just the default configuration copied here for convenience. Change as needed.
agent:
  obs_encoder:
    embed_dim: 256

    t10_image_tokenizer:
      shared_encoder: False
      image_encoder:
        pretrained: True

  # increase size of transformer according to what David uses
  noise_model:
    decoder:
      n_layers: 6
      layer_module:
        attention_module:
          n_heads: 8

logger:
  wandb:
    tags: ["rgb", "convnextv2"]
