# @package _global_

defaults:
  # patch the pointcloud and tokenize the patches
  - pointpatchrl
  - /tokenizers@agent.obs_encoder.t10_image_tokenizer: image_tokenizer
  - /transforms@data.gpu_batch_transforms.t99_norm_image: imagenet_norm
  - override /models/vision_encoder@agent.obs_encoder.t10_image_tokenizer.image_encoder: timm_convnextv2

agent:
  obs_encoder:
    embed_dim: 256

    # RGB image tokenizer
    t10_image_tokenizer:
      shared_encoder: False
      image_type: rgb
      image_encoder:
        pretrained: True

    # PointPatchRL tokenizer
    t10_patching:
      oversampling_ratio: 1.0

data:
  batch_size: ${floor_div:${platform.batch_size},4}  # 1/4 of typical batch size

logger:
  wandb:
    tags: ["pointcloud", "pointpatchrl", "rgb", "convnextv2"]
