python run_test.py  --config-name=robocasa_horeka_config \
            --multirun agents=beso_agent \
            agent_name=beso_xlstm \
            group=beso_decoder_only_dino \
            agents/model=beso/beso_dec_xlstm_rgbcasa \
            agents/obs_encoders=dinov2 \
            agents.if_film_condition=False \
            xlstm_encoder_blocks=8 \
            latent_dim=384 \
            seed=0,1,2