python run.py  --config-name=robocasa_horeka_config \
            --multirun agents=beso_agent \
            agent_name=beso_transformer \
            group=beso_decoder_only \
            agents/model=beso/beso_dec_transformer \
            epoch=100,200 \
            n_embd=256,512 \
            encoder_n_layer=6 \
            seed=0