# @package _global_

defaults:
  # trim idle frames from the start of each demonstration
  - /transforms@data.preprocess_transforms.t0-1_trim_idle: time_trim_idle
  
  # # since this dataset was recorded at ~20 fps, subsample by a factor of 2
  # - /transforms@data.preprocess_transforms.t0-2_subsample: time_subsample
  
  # We express rotations as quaternions. Predicted quaternions are normalized to unit length
  - /transforms@data.preprocess_transforms.t0-4_quaternions: rotations_quaternions

  # # convert actions to chunks of absolute target poses relative to the current frame
  # - /transforms@data.preprocess_transforms.t0-5_relative_actions: action_abs_to_relative_chunk
  # # normalize relative actions so that the max magnitude of each action dimension is 1.0
  # - /transforms@data.preprocess_transforms.t0-9_normalize_actions: action_norm_max
  
  # normalize absolute actions so that they lie within [-1,1]
  - /transforms@data.preprocess_transforms.t0-9_normalize_actions: action_norm_minmax

data:
  preprocess_transforms:
    t0-2_subsample:
      factor: 2

    t0-5_relative_actions:
      reference: current_ee_pose
