# @package _global_

defaults:
  # add a goal text based on the folder name of the demonstration
  - /transforms@data.preprocess.t8_add_goal: goal_from_foldername_real

  # compute a goal embedding token from the goal text
  # compute goal embeddings online to provide "data augmentation", since the embeddings
  # are not deterministic
  # since we don't optimize this model, it doesn't need to be in agent
  - /transforms@data.gpu_batch_transforms.t8_goal_embedding: goal_embedding_clip
