wandb:
  _target_: loggers.wandb.WandbLogger
  log_model: all  # all checkpoints are uploaded to wandb, even if only the last one is kept on disk

  # passed to wandb.init()
  project: "3d-sim2real"
  entity: "alr-3d-sim2real"
  notes: null
  tags: null
  reinit: finish_previous  # required for hydra sweeps with default launcher
  save_code: True  # save script used to start training, git commit, and patch
