_target_: transforms.action_binarize_gripper.BinarizeGripperActions
_partial_: True
threshold: null  # use half the max gripper width as threshold
hysteris_steps: 30  # issue a warning if state changes happen more frequently than this 
