_target_: transforms.dinov3.Dinov3FeatureExtractorTransform
_partial_: True

camera_keys: ${camera_keys}
feature_out_key: dinov3_features
tracking_points_key: dinov3_tracking_points
generate_tracking_points: True
rgb_key: ${rgb_key}