_target_: transforms.dinov3.Dinov3FeatureExtractorTransform
_partial_: True

camera_keys: [left_cam, right_cam]
feature_out_key: dinov3_features
tracking_points_key: dinov3_tracking_points
generate_tracking_points: True
