_target_: transforms.foundation_stereo.FoundationStereo
_partial_: True
engine_path: ${paths.fs_engines_dir}/foundation_stereo_small_3x480x640.plan
cam_keys: null # specify camera keys to replace, or null to replace all
remove_invisible: True
preprocess_batch_size: ${platform.fs_preprocess_batch_size}
