_target_: transforms.grounding_samv3.SamV3VideoSegmenterTransform
_partial_: True

camera_keys: ${camera_keys}
segmentation_text_source: key
segmenter_out_keys: [tool_segmentation, target_segmentation]
segmentation_text_keys: [tool, target]
rgb_key: ${rgb_key}
# max_frames_per_batch: 2
gdino_box_threshold: 0.4
out_device: cpu
add_backward_tracking: False