_target_: transforms.image_jitter_color.ColorJitterImage
_partial_: True
brightness: [0.0 , 1.0] # should be between (0, inf)
contrast: [0.0 , 1.0]   # should be between (0, inf)
saturation: [0.0 , 1.0] # should be between (0, inf)
hue: [-0.5 , 0.5]       # should be between (-0.5, 0.5)
