# name: voxel_downsample_pointcloud
_target_: transforms.nested_pointcloud_downsample_fps.FpsSamplePointCloud
_partial_: True
n_points: 40
random_start: True
pcd_keys:
  - target_points
  - tool_points
