# name: crop_pointcloud
_target_: transforms.pointcloud_crop.CropPointCloud
_partial_: True
x_range: [-1.0, 1.0]  # crop out the points in Narnia
y_range: [-1.0, 1.0]
z_range: [0.008, 1.0]   # just high enough to remove the table
warn_min_points: 100
