name: multiview_image_tokenizer
_target_: transforms.multiview_image_tokenizer.MultiviewImageTokenizer
_partial_: True

image_encoder:
  _target_: models.resnet.beso_resnet_encoder
  _partial_: True
  embed_dim: ${..embed_dim}
  pretrained_weights: null

embed_dim: ${..embed_dim}
shared_encoder: False
