_target_: transforms.samv3.SamV3VideoSegmenterTransform
_partial_: True

camera_keys: ${camera_keys}
segmentation_text_source: key
segmenter_out_keys: [obj_segmentation, target_segmentation]
segmentation_text_keys: [obj_name, target_name]
rgb_key: ${rgb_key}