_target_: transforms.time_trim_idle.TrimIdle
_partial_: True
compare: [joint_pos, action]
trim_type: ["start", "inside"]
pos_threshold: 0.0002
gripper_threshold: 0.0002
action_type: joint
window_size: 3
