_target_: transforms.sparse_to_pointcloud.SparseToPointCloudTrackOnly
_partial_: True
color: True
max_depth: 5.0
features: True
camera_keys: ${camera_keys}
track_key: tool_cotracker_tracks
visibility_key: tool_cotracker_visibility
features_key: dinov3_features
out_key: tool_points
rgb_key: ${rgb_key}