task_suite: furniture_bench

training:
  _target_: environments.datasets.furniture_bench.FurnitureBenchDataset
  root_dir: ${paths.data_dir}/furniture_bench/${..task}
  camera_names: [cam1, cam2, wristcam]
  obs_dim: 9
  action_dim: 7
  state_dim: 110
  max_len_data: 260
  window_size: 10
  traj_per_task: 10

simulation:
  _target_: environments.simulations.isaac.IsaacSim
  scene: 
  render: False
  num_episode: 20
  max_step_per_episode: 600
