dataset:
  _target_: environments.datasets.libero_dataset.LiberoDataset
  # BALAZS: refactor absolute path
  data_directory: /home/balazs/repos/external/LIBERO/libero/datasets/${task_suite}
  obs_dim: 9
  action_dim: 7
  state_dim: 110
  max_len_data: 260
  window_size: 10
  traj_per_task: 10
