python run.py  --config-name=libero_horeka_config \
            --multirun agents=beso_agent \
            agent_name=beso_xlstm \
            group=beso_decoder_only \
            agents/model=beso/beso_dec_xlstm \
            task_suite=libero_10 \
            traj_per_task=10 \
            xlstm_encoder_blocks=8 \
            scaler_type='minmax' \
            seed=0,1,2