python run.py  --config-name=libero_horeka_ablation_config \
            --multirun agents=beso_agent \
            agent_name=beso_xlstm \
            group=beso_encoder_decoder \
            agents/model=beso/beso_encdec_xlstm \
            task_suite=libero_10 \
            traj_per_task=10,50 \
            xlstm_decoder_vocab_size=10 \
            xlstm_decoder_adaLN_zero=True \
            seed=0,1,2