python run.py  --config-name=libero_horeka_ablation_config \
            --multirun agents=beso_agent \
            agent_name=beso_xlstm \
            group=beso_encoder_decoder \
            agents/model=beso/beso_encdec_xlstm \
            task_suite=libero_10 \
            traj_per_task=10 \
            scaler_type='minmax' \
            xlstm_encoder_blocks=4 \
            xlstm_decoder_blocks=8 \
            seed=0