# this environment variable is set by rootutils.setup_root in every script
root_dir: ${oc.env:PROJECT_ROOT}

# path to data directory
data_dir: ${paths.root_dir}/datasets
calibration_data_dir: ${paths.root_dir}/calibration_data

# preprocessed data directory
preprocessed_dir: ${paths.root_dir}/preprocessed_datasets
debug_preprocessed_dir: ${paths.root_dir}/debug_preprocessed_datasets
zipped_preprocessed_dir: ${paths.root_dir}/zipped_preprocessed_datasets

# path to logging directory
log_dir: ${paths.root_dir}/logs

# path to output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/default.yaml`
# use it to store all files generated during the run, like ckpts and metrics
output_dir: ${hydra:runtime.output_dir}

# path for storing videos for validation in simulation 
recording_dir: ${paths.root_dir}/recordings

# because this gets saved into the transforms, don't resolve the (system-specific) absolute path
# instead, $PROJECT_ROOT should be resolved at runtime
fs_engines_dir: $PROJECT_ROOT/foundation_stereo_models
