_target_: agents.models.equibot.equibot_policy.EquiBotPolicy
_recursive_: false

obs_mode: pc
ac_mode: rel
use_torch_compile: false
pred_horizon: ${pred_seq_len}
obs_horizon: ${obs_seq_len}
action_horizon: ${act_seq_len}
noise_scheduler:
  _target_: diffusers.schedulers.scheduling_ddpm.DDPMScheduler
  num_train_timesteps: 100
  beta_schedule: squaredcos_cap_v2
  clip_sample: true
  prediction_type: epsilon
pc_encoder:
  _target_: agents.models.equibot.vision.sim3_encoder.SIM3Vec4Latent
  device: ${device}
  c_dim: 32
  backbone_type: vn_pointnet
  backbone_args:
    h_dim: 32
    c_dim: ${agents.model.pc_encoder.c_dim}
    num_layers: 4
    knn: 8
noise_pred_net:
  _target_: agents.models.equibot.utils.equivariant_diffusion.conditional_unet1d.VecConditionalUnet1D
  input_dim: 2
  cond_dim: 72
  scalar_cond_dim: ${agents.model.obs_horizon}
  scalar_input_dim: 1
  diffusion_step_embed_dim: ${agents.model.noise_pred_net.cond_dim}
  cond_predict_scale: False
eef_dim: 13
device: ${device}