_target_: agents.models.bc.bc.BC_Policy
_recursive_: false

defaults:
  - backbones: transformer
  - obs_encoders: resnet

if_film_condition: False
device: ${device}
state_dim: ${obs_dim}
latent_dim: ${latent_dim}
