_target_: agents.models.beso.beso.BESO
_recursive_: false

defaults:
  - backbones: transformer
  - obs_encoders: resnet

action_dim: ${action_dim}
action_seq_len: ${act_seq_len}

device: ${device}
# diffusion params
sampler_type: 'ddim'
num_sampling_steps: 4
sigma_data: 0.5
sigma_min: 0.001
sigma_max: 80
noise_scheduler: 'exponential'
sigma_sample_density_type: 'loglogistic'

use_lr_scheduler: true
latent_dim: ${latent_dim}

model:
  _target_: agents.models.beso.models.edm_diffusion.score_wrappers.GCDenoiser
  _recursive_: false

  sigma_data: 0.5

  inner_model:
    _target_: agents.models.beso.models.networks.mdt_transformer.MDTTransformer
    action_dim: ${action_dim}
    obs_dim: ${latent_dim}
    goal_dim: ${goal_dim}
    proprio_dim: 8
    goal_conditioned: False
    embed_dim: ${latent_dim}
    n_dec_layers: 6
    n_enc_layers: 4
    goal_seq_len: ${goal_window_size}
    obs_seq_len: 4 #4 camers ${obs_seq_len}
    action_seq_len: ${act_seq_len}
    embed_pdrob: 0
    goal_drop: 0
    attn_pdrop: 0.3
    resid_pdrop: 0.1
    mlp_pdrop: 0.05
    # Architecture details
    n_heads: 8
    device: ${device}
    linear_output: True
    use_rot_embed: False
    use_abs_pos_emb: True
    bias: false
    use_ada_conditioning: True
    use_noise_encoder: False # only relevant for ada_conditioning
    use_modality_encoder: True
    use_mlp_goal: False

#language_goal:
#  _target_: agents.mdt.models.networks.clip_lang_encoder.LangClip
#  # mdt.models.encoders.clip_tokens.LangClip
#  _recursive_: false
#
#  # device: ${device}
#  # pretrained_model: ${clip_lang_model_name}
#  model_name: ${clip_lang_model_name}
#  # 16 or 32 "RN101", "RN50x4", "RN50x16", "ViT-B/32", "ViT-B/16"

optimizer:
  _target_: torch.optim.AdamW
  transformer_weight_decay: 0.05
  obs_encoder_weight_decay: 0.05
  learning_rate: 1e-4
  betas: [0.9, 0.9]

lr_scheduler:
  lr_scheduler:
    init_lr: 1e-4  # This is the peak or maximum learning rate
    init_lr_scale: 0.1  # This is the ratio of initial learning rate to peak learning rate
    final_lr_scale: 1e-6  # This is the ratio of final learning rate to peak learning rate
    total_steps: 50000  # Example total steps, adjust as needed
    phase_ratio: "(0.02, 0.08, 0.9)"
    lr: 1e-4
