# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.ModelCheckpoint.html

model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ${paths.output_dir}/checkpoints # directory to save the model file
  verbose: True # verbosity mode
  save_weights_only: True # if True, then only the model’s weights will be saved
  every_n_epochs: 10 # number of epochs between checkpoints
  save_top_k: -1 # keep all checkpoints on disk, not just the last one
