defaults:
  - data: real_robot
  - data@agent.replay_data: one_leg_alr_metaquest
  - agent: null_agent
  - callbacks:
  - logger:
  - python_logging: default
  - paths: default
  - hydra: default
  - _self_
  - platform: default
  - optional local: default
  - debug: verbose

# task name, determines output directory path
job_type: open_loop_replay

agent:
  replay_data:
    dataset:
      action_seq_len: 1  # action chunking unnecessary for open-loop replay
      load_subset: 0.1
  fps: 20

trainer:
  default_root_dir: ${paths.output_dir}
  enable_progress_bar: False
