# usage: predict.py -cn open_loop_replay

defaults:
  - data: real_robot
  - agent: null_agent
  - data@agent.replay_data: one_leg_alr_20250724
  - callbacks:
  - logger:
  - python_logging: default
  - paths: default
  - hydra: default
  - platform: default
  - optional local: default
  - debug: verbose
  # instead of converting to relative action chunks, we transform the entire
  # trajectory into the reference frame of the first action
  - override transforms@agent.replay_data.preprocess_transforms.t0-3_relative_actions: action_abs_to_relative
  - _self_

# task name, determines output directory path
job_type: open_loop_replay

callbacks:
  sync_initial_robot_pose:
    _target_: callbacks.sync_initial_robot_pose.SyncRobotResetPose
    space: task  # sync initial task space positions
    cartesian_offset: [0.0, 0.0, 0.04]  # lift by 4cm so as not to collide with the U-object

agent:
  replay_data:
    dataset:
      action_seq_len: 1  # action chunking unnecessary for open-loop replay
      load_subset: [0]  # load selected trajectory
      overwrite_preprocessed: True  # don't worry about overwriting the preprocessed data since we are using a small subset

    preprocess_transforms:
      t0-3_relative_actions:
        reference: first_ee_pose  # use the first ee_pose as the reference frame to convert to relative
      # t0-4_normalize_actions: null

  fps: 10

data:
  eval_mode: env  # evaluate in the real environment
  env_dataset:
    env:
      cameras: null  # we don't need cameras for open-loop replay
    action_horizon: null  # execute all incoming actions
    fps: null  # disable the redundant fps limiter in the environment
  
# since we load a small subset of the data, store preprocessed data in another folder
paths:
  preprocessed_dir: ${paths.debug_preprocessed_dir}

trainer:
  default_root_dir: ${paths.output_dir}
  enable_progress_bar: False
  accelerator: cpu  # no need for GPU
