defaults:
  - /robot/teleop_pair@data_collection_manager.teleoperation_pair: panda
  - /cameras@data_collection_manager.cameras.gripper_cam: realsense_d405_218622270040
  - /cameras@data_collection_manager.cameras.right_cam: zed_mini_16055244
  - /cameras@data_collection_manager.cameras.left_cam: zed_mini_17008863
  - debug: verbose
  - _self_

data_collection_manager:
  data_dir: /tmp/sim2real/recordings/lamp
  step_hz: 15
