defaults:
  - callbacks:
  - logger:
  - python_logging: default
  - paths: default
  - hydra: default
  - _self_
  - platform: default
  - optional local: default
  - debug: verbose

# task name, determines output directory path
job_type: test_sim

# either specify a complete checkpoint path...
log_dir:
# ...or specify the wandb run name
artifact_run_name:
# project and entity are only needed if they differ from the settings in the wandb logger config
artifact_project: 3d-sim2real
artifact_entity: alr-3d-sim2real
# by default, the latest version of the artifact is used
artifact_version:

data:
  env_dataset:
    action_horizon: 5  # modify if desired
  eval_mode: env

trainer:
  default_root_dir: ${paths.output_dir}
  enable_progress_bar: False
  log_every_n_steps: 10
