defaults:
  - data: real_robot
  - callbacks:
  - logger:
  - python_logging: default
  - paths: default
  - hydra: default
  - transforms@agent.obs_encoder.t3_render: render_cameras
  - _self_
  - experiment: depth_only
  - platform: default
  - optional local: default
  - debug: verbose

# task name, determines output directory path
job_type: test_real

logger:
  wandb:
    project: test_real
    job_type: eval

# either specify a complete checkpoint path...
log_dir:
# ...or specify the wandb run name
artifact_run_name: 0u1n2wcf
# project and entity are only needed if they differ from the settings in the wandb logger config
artifact_project: 3d-sim2real
artifact_entity: alr-3d-sim2real
# by default, the latest version of the artifact is used
artifact_version:

trainer:
  accelerator: gpu
  devices: auto
  # precision: 16-true
  default_root_dir: ${paths.output_dir}
  enable_progress_bar: False
  log_every_n_steps: 10

torch:
  set_float32_matmul_precision: medium
