# usage: python test.py -cn test_maniskill

defaults:
  - data: maniskill_cam1_joint_delta_pos_w_goal  # BackCompat
  # log test results to new wandb run, since test parameters affect results
  - logger: wandb
  - python_logging: default
  - paths: default
  - hydra: checkpoint_dir_naming
  # - transforms@data.gpu_batch_transforms.t90_render: render_cameras
  # - transforms@data.gpu_batch_transforms.t90_render_pcd: render_pointcloud
  - _self_
  - platform: default
  - optional local: default
  - debug: verbose

# task name, determines output directory path
job_type: test_sim

checkpoint:
  # either specify a complete checkpoint path...
  log_dir:
  # ...or specify the wandb run name
  wandb_run_id:  # REPLACE with desired wandb run id
  # project and entity are only needed if they differ from the settings in the wandb logger config
  wandb_project: 3d-sim2real
  wandb_entity: alr-3d-sim2real
  epochs: [89, 119, 149]  # options: last, all, last_n (default: last)
  artifact_version:  # e.g. latest, v0, v1, v2, ... (overrides epochs if set)
  use_artifact: False  # sets the current run to be a consumer of the artifact (doesn't make sense for resumed runs)

agent:
  num_sampling_steps: 10  # modify if desired

data:
  eval_mode: env
  env:
    num_episodes: 50  # 150 episodes in total across 3 checkpoints
    action_horizon: 10  # modify if desired

    env:
      env_id:  # REPLACE with desired environment name
      wrappers:
        record_video:
          num_episodes: ${data.env.num_episodes}  # number of episodes to record
          fps: 60  # increase if the videos are too long

  preprocess:
    t99_cleanup: null  # disable cleanup transform added by default

  gpu_batch_transforms:
    t90_render:
      stream_names: [rgb, depth]
    t90_render_pcd:
      render_camera_poses: True
      render_ee_pose: False
      render_action: False

logger:
  wandb:
    # use the notes and tags from the training run
    # don't use the overrides passed to the test.py script
    notes_from_overrides: False
    tags_from_overrides: False

trainer:
  default_root_dir: ${paths.output_dir}
  enable_progress_bar: False
  log_every_n_steps: 10
  inference_mode: False  # TODO: why is this needed?
