# usage: python test.py -cn test_on_dataset

defaults:
  - data: one_leg_alr_20250724
  - callbacks: null  # TODO: test eval_trajectories
  - logger:
  - python_logging: default
  - paths: default
  - hydra: checkpoint_dir_naming
  - _self_
  - platform: default
  - optional local: default
  - debug: verbose

# task name, determines output directory path
job_type: test_on_dataset

checkpoint:
  # either specify a complete checkpoint path...
  log_dir:
  # ...or specify the wandb run name
  wandb_run_id:
  # project and entity are only needed if they differ from the settings in the wandb logger config
  wandb_project: 3d-sim2real
  wandb_entity: alr-3d-sim2real
  epochs: last  # options: last, all, last_n (default: last)
  artifact_version:  # e.g. latest, v0, v1, v2, ... (overrides epochs if set)
  use_artifact: false  # sets the current run to be a consumer of the artifact (doesn't make sense for resumed runs)

data:
  eval_mode: dataset
  # dataset:
  #   action_seq_len: 10  # you may need to reprocess the dataset if you enable this

trainer:
  default_root_dir: ${paths.output_dir}
  log_every_n_steps: 10
