# usage: python test.py -cn test_robocasa

defaults:
  - data: robocasa  # overwrite env config from training run
  # log test results to new wandb run, since test parameters affect results
  - logger: wandb
  - python_logging: default
  - paths: default
  - hydra: checkpoint_dir_naming
  # - transforms@data.gpu_batch_transforms.t90_render: render_cameras
  # - transforms@data.gpu_batch_transforms.t90_render_pcd: render_pointcloud
  # - /transforms@data.gpu_batch_transforms.t99_render_pcd: pakt_render_pointcloud
  - _self_
  - platform: default
  - optional local: default
  - debug: verbose

# task name, determines output directory path
job_type: test_robocasa

checkpoint:
  # either specify a complete checkpoint path...
  log_dir:
  # ...or specify the wandb run name
  wandb_run_id: ??? # REPLACE with desired wandb run id
  # project and entity are only needed if they differ from the settings in the wandb logger config
  wandb_project: PAKT_debug
  wandb_entity: nicolasschreiber
  epochs: last  # options: last, all, last_n (default: last)
  artifact_version:  # e.g. latest, v0, v1, v2, ... (overrides epochs if set)
  use_artifact: False  # sets the current run to be a consumer of the artifact (doesn't make sense for resumed runs)

agent:
  num_sampling_steps: 10  # modify if desired

data:
  eval_mode: env
  env:
    num_episodes: 50  # 150 episodes in total across 3 checkpoints

    env_name: null # REPLACE with desired environment name
    num_envs: 4
    parallel: null  # automatically use parallel if num_envs > 1
    action_horizon: 20  # modify if desired
    # top_level_keys: segmentation_ids

    camera_names:  # specify the camera names to use for observations
      - robot0_agentview_left
      - robot0_agentview_right

    record_video:
      video_folder: ${hydra:run.dir}/videos
      num_episodes: 20  # record videos for the first 20 episodes
      fps: 30  # speed up the videos by using a higher fps
      disabled: True  # set to True to enable video recording

  prepreprocess:
    t99_cleanup: null  # disable cleanup transform added by default
  preprepreprocess:  
    t00_apply_robocasa_segmentations:
      camera_keys: [robot0_agentview_left, robot0_agentview_right]
    t03_dinov3:
      camera_keys: [robot0_agentview_left, robot0_agentview_right]
    t04_cotracker: null
    t05_target_to_featured_pointcloud:
      mode: mask
      mask_key: target_segmentation
      camera_keys: [robot0_agentview_left, robot0_agentview_right]
      # _target_: transforms.sparse_to_pointcloud.SparseToPointCloudMerged
    t06_tool_to_featured_pointcloud:
      mode: mask
      mask_key: tool_segmentation
      camera_keys: [robot0_agentview_left, robot0_agentview_right]
      # _target_: transforms.sparse_to_pointcloud.SparseToPointCloudMerged
    t99_cleanup: null  # disable cleanup transform added by default
  
  gpu_batch_transforms:
    t04_random_rotation: Null

logger:
  wandb:
    job_type: test_sim  # group with other simulation test runs in WandB
    # use the notes and tags from the training run
    # don't use the overrides passed to the test.py script
    project: ${checkpoint.wandb_project}
    notes_from_overrides: False
    tags_from_overrides: False

trainer:
  default_root_dir: ${paths.output_dir}
  enable_progress_bar: False
  log_every_n_steps: 10
  inference_mode: False  # TODO: why is this needed?
