# usage: python test.py -cn test_isaac

defaults:
  - data: isaac  # only necessary for runs that were trained with old environment config
  - data/wrappers@data.env_dataset.env.wrappers: record_video  # record videos
  # log test results to new wandb run, since test parameters affect results
  - logger: wandb
  - python_logging: default
  - paths: default
  - hydra: default
  - _self_
  - platform: default
  - optional local: default
  - debug: verbose

# task name, determines output directory path
job_type: test_sim

checkpoint:
  # either specify a complete checkpoint path...
  log_dir:
  # ...or specify the wandb run name
  wandb_run_id:
  # project and entity are only needed if they differ from the settings in the wandb logger config
  wandb_project: 3d-sim2real
  wandb_entity: alr-3d-sim2real
  epochs: last  # options: last, all, last_n (default: last)
  artifact_version:  # e.g. latest, v0, v1, v2, ... (overrides epochs if set)
  use_artifact: false  # sets the current run to be a consumer of the artifact (doesn't make sense for resumed runs)

data:
  eval_mode: env
  env_dataset:
    num_episodes: 10
    action_horizon: 10  # modify if desired

    env:
      env_cfg:
        episode_length_s: 10
    
      wrappers:
        record_video:
          num_episodes: ${data.env_dataset.num_episodes}  # number of episodes to record
          fps: 50  # increase if the videos are too long

trainer:
  default_root_dir: ${paths.output_dir}
  enable_progress_bar: False
  log_every_n_steps: 10
