defaults:
  - data: one_leg_alr_20250724
  - agent: beso_agent
  - callbacks:
    - model_checkpoint
    - model_summary
    - batch_size_finder
  - logger: 
    - wandb
  - python_logging: default
  - paths: default
  - hydra: default
  - _self_
  - obs_modality: rgbd_imagenet
  - obs_encoder: rgb_resnet18
  - experiment: null
  - platform: default
  - optional local: default
  - debug: single_batch

# task name, determines output directory path
job_type: train

logger:
  wandb:
    job_type: ${job_type}

seed: null

data:
  eval_mode: 0.05  # "env" to validate in simulation or a float to validate on subset of data

trainer:
  default_root_dir: ${paths.output_dir}
  deterministic: True
  max_epochs: 100
  log_every_n_steps: 10
  check_val_every_n_epoch: 10
  enable_model_summary: False  # we print model summary manually with a callback
