defaults:
  - data: one_leg_alr_metaquest
  - agent: beso_agent
  - callbacks:
    - model_checkpoint
    - model_summary
  - logger: 
    - wandb
    - csv
  - python_logging: default
  - paths: default
  - hydra: default
  - _self_
  - experiment: rgb_multiresnet
  - platform: default
  - optional local: default
  - debug: single_batch

# task name, determines output directory path
job_type: train

seed: null

data:
  eval_mode: null  # "env" to validate in simulation or a float to validate on subset of data

trainer:
  default_root_dir: ${paths.output_dir}
  max_epochs: 100
  log_every_n_steps: 10
  check_val_every_n_epoch: 10
  limit_val_batches: 0  # disable validation, e.g. if we don't want to initialize a simulation
  enable_model_summary: False  # we print model summary manually with a callback
