defaults:
  - data: real_robot
  - agent: null_agent
  - callbacks:
  - logger:
  - python_logging: default
  - paths: default
  - hydra: default
  - obs_modality: real_pointclouds
  - transforms@agent.obs_encoder.t9_render: render_pointcloud
  - _self_
  - platform: default
  - optional local: default
  - debug: verbose

# task name, determines output directory path
job_type: visualize_real_robot

data:
  gpu_batch_transforms:
    t3_to_pcd:
      color: True

trainer:
  default_root_dir: ${paths.output_dir}
  enable_progress_bar: False
