# Render the first trajectory in the dataset, either as RGB images or point clouds.
# usage: python predict.py -cn visualize_dataset

defaults:
  - data: ???
  - agent: null_agent
  - callbacks: null
  - logger: null
  - python_logging: default
  - paths: default
  - hydra: default
  - preprocessing: null
  - obs_modality: null
  - transforms@data.gpu_batch_transforms.t90_render: render_cameras
  # - transforms@data.gpu_batch_transforms.t90_render_pcd: render_pointcloud
  - platform: default
  - optional local: default
  - debug: quick  # cannot use single_batch here, because we want to visualize the whole trajectory
  - _self_

# task name, determines output directory path
job_type: visualize_dataset

data:
  eval_mode: dataset
  batch_size: 1  # required for visualization
  action_seq_len: 1  # no action chunks, because only the first frame is rendered
  
  dataset:
    load_subset: [0]  # load selected trajectory

  preprocess:
    t15_to_pcd:
      color: True  # add colors to pointclouds, in case we render pointclouds

    # don't remove any data streams, so we can visualize them
    t1_drop: null
    t99_cleanup: null

  gpu_batch_transforms:
    t90_render:
      stream_types: [rgb, depth]
      stream_names: [rgb, left, depth]

    t90_render_pcd:
      render_camera_poses: False
      render_ee_pose: False
      render_action: False

agent:
  fps: 10

trainer:
  default_root_dir: ${paths.output_dir}
  enable_progress_bar: False
