defaults:
  - data: real_robot
  - /cameras/calibration@data.env.env.cameras: 2025-09-16
  - agent: null_agent
  - callbacks:
  - logger:
  - python_logging: default
  - paths: default
  - hydra: default
  - obs_modality: real_pointclouds
  - transforms@data.gpu_batch_transforms.t9_render_pcd: render_pointcloud
  - _self_
  - platform: default
  - optional local: default
  - debug: verbose

# task name, determines output directory path
job_type: visualize_real_robot

data:
  eval_mode: env
  env:
    env:
      human_control: True  # allow the robot to move freely
  
  gpu_batch_transforms:
    t3_to_pcd:
      color: True

trainer:
  default_root_dir: ${paths.output_dir}
  enable_progress_bar: False
