defaults:
  - data: one_leg_alr_metaquest
  - agent: null_agent
  - callbacks: null
  - logger: null
  - python_logging: default
  - paths: default
  - hydra: default
  - experiment:
    - rgb_multiresnet
    - render
  - _self_
  - platform: default
  - optional local: default
  - debug: verbose

# task name, determines output directory path
job_type: visualize_dataset

data:
  batch_size: 1
  eval_mode: dataset
  dataset:
    load_subset: 0.05
  gpu_batch_transforms:
    4_norm: null  # do not normalize when rendering

trainer:
  accelerator: gpu
  devices: 1
  # precision: 16-true
  default_root_dir: ${paths.output_dir}
  enable_progress_bar: False

torch:
  set_float32_matmul_precision: medium
