# Render the first trajectory in the dataset, either as RGB images or point clouds.
# usage: python predict.py -cn visualize_dataset

defaults:
  - data: one_leg_alr_20250724
  - agent: null_agent
  - callbacks: null
  - logger: null
  - python_logging: default
  - paths: default
  - hydra: default
  - obs_modality: rgbd_imagenet
  # - transforms@agent.obs_encoder.t9_render: render_cameras
  # - obs_modality: sim_pointclouds
  # - transforms@agent.obs_encoder.t9_render_pcd: render_pointcloud
  - platform: default
  - optional local: default
  - debug: quick  # cannot use single_batch here, because we want to visualize the whole trajectory
  - _self_

# task name, determines output directory path
job_type: visualize_dataset

data:
  batch_size: 1  # required for visualization
  eval_mode: dataset
  dataset:
    load_subset: [0]  # load selected trajectory
    action_seq_len: 1  # no action chunks, because only the first frame is rendered
    # # disabled `debug_preprocess` because some transforms only work in preprocessing
    # debug_preprocess: True  # prepend preprocess transforms to cpu transforms

  preprocess_transforms:
    t2_resize:
      shape: 512  # increase resolution for better visualization

    t2_resize_for_pcd:
      shape: 256  # increase resolution for better visualization (but not too high, due to memory constraints)
    
    t3_crop_image: null  # disable cropping, because we want to visualize the whole image
    
    t3_to_pcd:
      color: True  # add colors to pointclouds, in case we render pointclouds

    t4_crop_pcd:
      x_range: [0.0, 1.0]  # increase to keep robot base in view
      y_range: [-0.4, 0.4]
      z_range: [0.004, 0.5]  # increase to keep robot arm in view

  gpu_batch_transforms:
    t4_norm_image: null  # disable imagenet normalization of colors

    t5_voxel_downsample:
      size: 0.004  # increase resolution for better visualization

agent:
  fps: 15
  obs_encoder:
    t9_render:
      stream_names: [rgb, depth]
    t9_render_pcd:
      render_camera_poses: False
      render_ee_pose: True
      render_action: True

trainer:
  default_root_dir: ${paths.output_dir}
  enable_progress_bar: False
