# @package _global_

# Instead of setting values (e.g. batch_size) directly in other parts of the
# config (e.g. data.dataset.batch_size), we put these values here and allow
# other configs to interpolate them. This gives us more flexibility to compose
# configs, e.g. from the obs_modality, experiments, debug settings, etc.
platform:
  name: workstation
  num_workers: 4
  batch_size: 256
  pin_memory: True  # test if True is faster, but it might not be
  prefetch_factor: 2  # reduce memory usage for on-disk datasets
  fs_preprocess_batch_size: 192

torch:
  set_float32_matmul_precision: medium
  print_options:
    linewidth: 120

trainer:
  accelerator: gpu
  devices: 1
  # https://lightning.ai/docs/fabric/stable/fundamentals/precision.html
  precision: bf16-mixed
