# @package _global_

platform:
  name: workstation
  num_workers: 16  # make available for any config to use
  batch_size: 256  # make available e.g. for experiment configs to modify
  pin_memory: False  # test if True is faster, but it might not be

torch:
  set_float32_matmul_precision: medium

trainer:
  deterministic: True
  accelerator: gpu
  devices: auto
  # precision: 16-true
