# @package _global_

defaults:
  - slurm
  - override /hydra/launcher: submitit_slurm
  - _self_

platform:
  name: horeka
  num_workers: 36  # horeka node has 152 cores = 38 cores per GPU

data:
  eval_mode: null  # we don't want to run IsaacSim on Horeka

paths:
  data_dir: ${oc.env:TMPDIR}/datasets

trainer:
  enable_progress_bar: False  # don't clutter up the logs

hydra:
  mode: MULTIRUN
  launcher:
    account: ???
    timeout_min: 2880
    partition: accelerated
    gres: gpu:1
    cpus-per-task: ???
    setup:
      # Create wandb folder in fast, job-local storage: https://www.nhr.kit.edu/userdocs/horeka/filesystems/#tmpdir
      # NOTE: wandb folder will be deleted after job completion, but by then it will have synced with server
      - export WANDB_DIR=$TMPDIR/wandb
      - mkdir -pv $WANDB_DIR
      - wandb enabled
