# @package _global_

defaults:
  - kit_hpc
  - _self_

platform:
  name: horeka
  num_workers: 16  # accelerated node has 152 cores = 38 cores per GPU

hydra:
  launcher:
    account: hk-project-p0022253
    timeout_min: 2880  # 48 hours
    partition: accelerated
    exclude: null # add any broken nodes here
    constraint: LSDF  # needed for the LSDF to be mounted on compute nodes
    gres: gpu:1
    cpus_per_task: 38
