# @package _global_

defaults:
  - default
  - slurm
  - _self_

paths:
  # absolute path to our project inside the LSDF, should work for all users
  data_dir: $LSDF/kit/iar/projects/alr_3d-sim2real/demonstrations
  # $TMPDIR, not ${oc.env:TMPDIR}, so it gets resolved inside the job, not on the login node
  preprocessed_dir: $TMPDIR/preprocessed_data
  debug_preprocessed_dir: $TMPDIR/debug_preprocessed_data

data:
  dataset:
     overwrite_preprocessed: True  # don't crash just because zipped datasets are out of date
  batch_size: 512  # increase the nominal batch size, since we have more memory

hydra:
  launcher:
    setup:
      # unzip training data onto fast, job-local storage: https://www.nhr.kit.edu/userdocs/horeka/filesystems/#tmpdir

      # get the relative path inside the preprocessed_dir where the dataset expects the preprocessed data
      # (e.g. PREPROCESS_PATH="metaquest3_2025-07-24/multiview_image")
      - PREPROCESS_NAME=$(realpath --canonicalize-missing --no-symlinks --relative-to=${paths.preprocessed_dir} ${data.dataset.preprocessed_dir})
      - echo "PREPROCESS_NAME=$PREPROCESS_NAME"

      # Note: this path gets resolved twice. First hydra resolves ${paths.preprocessed_dir} on the login node, then
      # bash resolves $TMPDIR inside the job
      - mkdir -pv ${data.dataset.preprocessed_dir}
      - if [[ -f ${paths.zipped_preprocessed_dir}/$PREPROCESS_NAME.tar.zst ]]; then
      -   echo "$(date '+%F_%H:%M:%S') - Extracting ${paths.zipped_preprocessed_dir}/$PREPROCESS_NAME.tar.zst to ${data.dataset.preprocessed_dir}..."
      -   tar -I "zstd -T0" -xf ${paths.zipped_preprocessed_dir}/$PREPROCESS_NAME.tar.zst -C ${data.dataset.preprocessed_dir}
      -   echo "$(date '+%F_%H:%M:%S') - Done."
      - else
      -   echo "No zipped preprocessed data found at ${paths.zipped_preprocessed_dir}/$PREPROCESS_NAME.tar.zst"
      - fi

      # ensure wandb isn't disabled by accident
      - wandb enabled

      # force hydra to show full error messages
      - export HYDRA_FULL_ERROR="1"
