# @package _global_

defaults:
  - override /hydra/launcher: submitit_slurm
  - override /hydra: numbered_subdir  # ensure that folder names are not too long
  - _self_

trainer:
  enable_progress_bar: False  # doesn't get captured correctly, making the log hard to read

hydra:
  mode: MULTIRUN
  launcher:
    # remove the leading "." so it's not hidden
    submitit_folder: ${hydra.sweep.dir}/submitit/%j
