_target_: agents.models.vqbet.vqvae.VqVae
_recursive_: false

#obs_dim: ${obs_dim}
action_dim: ${action_dim}
action_seq_len: ${act_seq_len}
n_latent_dims: 512
vqvae_n_embed: 32
vqvae_groups: 4
device: ${device}
encoder_loss_multiplier: 1.0
