# !!! IMPORTANT !!!
# There is a known limitation in the Omniverse camera model:
# https://github.com/isaac-sim/IsaacLab/blob/91ad4944f2b7fad29d52c04a5264a082bcaad71d/source/isaaclab/isaaclab/sensors/camera/camera.py#L239
#
# As a result, we cannot directly use the optical center values (cx, cy) obtained through calibration or optimization.
# Instead, the optical center must be set to the center of the image as follows:
#
#     cx = width / 2
#     cy = height / 2
#
# Otherwise, the camera will be incorrectly configured, and depth images will be distorted.
# This distortion is not always apparent when inspecting single depth images, but it becomes apparent when fusing depth data from multiple cameras (e.g., in point cloud generation or 3D reconstruction).
intrinsics:
  resolution:
    480x640:  [385.566, 0.0, 320.0, 0.0, 385.566, 240.0, 0.0, 0.0, 1.0]

extrinsics: [0.0,  0.7071, -0.7071,  0.13, -1.0,  0.0,  0.0,  0.0, 0.0,  0.7071,  0.7071, -0.01,  0.0,  0.0,  0.0,  1.0]