defaults:
  - _self_
  - noise_model: decoder_only
  - backbone@noise_model.decoder: transformer
  - time_encoder@noise_model.time_encoder: learned
  - sigma_encoder@noise_model.sigma_encoder: beso
  - action_head@noise_model.action_head: linear
  - optimizer: adamw
  - lr_scheduler: none
  # - obs_encoder: default
  - obs_encoder/depth: raw
  - obs_encoder/pixels: raw
  - obs_encoder/tokenizer: pointpatch
  - obs_encoder/robot_state_encoder: linear
  - scaler: minmax
  - language_encoder: none
  - sampler: ddim
  - noise_distribution: loglogistic
  - noise_schedule: exponential

_target_: agents.beso_agent.BesoAgent

# Arguments passed at runtime:
# dataset: ???

obs_encoder:
  _target_: agents.encoders.encoder.ObservationEncoder
  _partial_: True
  embed_dim: 256

# diffusion params
num_sampling_steps: 4
sigma_data: 0.5
sigma_min: 0.001
sigma_max: 80

decay_ema: 0.995
