defaults:
  - model: beso/beso_dec_transformer
  - noise_distribution: loglogistic
  - noise_schedule: exponential
  - sampler: ddim
  - scaler@action_scaler: minmax
  - obs_encoder: default
  - language_encoder: clip
  - optimizer: adamw
  - lr_scheduler: tristage

_target_: agents.beso_agent.BesoAgent

# Arguments required at runtime:
# dataset: ???

if_film_condition: False
if_robot_states: False

#language_goal:
#  _target_: agents.mdt.models.networks.clip_lang_encoder.LangClip
#  # mdt.models.encoders.clip_tokens.LangClip
#  _recursive_: false
#
#  # device: ${device}
#  # pretrained_model: ${clip_lang_model_name}
#  model_name: ${clip_lang_model_name}
#  # 16 or 32 "RN101", "RN50x4", "RN50x16", "ViT-B/32", "ViT-B/16"

latent_dim: ${latent_dim}

obs_seq_len: ${obs_seq_len}
act_seq_len: ${act_seq_len}

# diffusion params
num_sampling_steps: 4
sigma_data: 0.5
sigma_min: 0.001
sigma_max: 80

ckpt_path: null
