defaults:
  - _self_
  - noise_model: decoder_only
  - optimizer: adamw
  - lr_scheduler: none
  - /transforms@obs_encoder.4_robot_state: linear_robot_state_encoder
  - scaler: minmax
  - goal_encoder: none
  - sampler: ddim
  - noise_distribution: loglogistic
  - noise_schedule: exponential

_target_: agents.beso_agent.BesoAgent

# Arguments passed at runtime:
# specs: ???

obs_encoder:
  embed_dim: 256

# diffusion params
num_sampling_steps: 4
sigma_data: 0.5
sigma_min: 0.001
sigma_max: 80

ema_decay: 0.995
