defaults:
  - _self_
  - noise_model: pakt_decoder_only
  - noise_distribution: loglogistic
  - noise_schedule: exponential
  - sampler: ddim
  - optimizer: adamw
  - lr_scheduler: warmup_cosine
  - goal_encoder: null

_target_: agents.pakt_beso_agent.BesoAgent

# Arguments passed at runtime:
# specs: ???
precondition_type: edm
obs_encoder:
  embed_dim: 512

keypoint_loss_dropout: 0.0 # 0.0 means no dropout; 1.0 means drop all keypoints (i.e. only use the MLP loss on the gripper pose)
keypoint_loss_scaling: 0.8 # scales the keypoint loss relative to the gripper pose loss
action_loss_scaling: 1.2 # scales the gripper pose loss relative to the keypoint loss

qk_norm_weight_decay: 0.01           # <-- new; null disables the qk-norm group
exclude_norms_from_weight_decay: true # <-- new


# diffusion params
num_sampling_steps: 10
sigma_data: 0.15
sigma_min: 0.01
sigma_max: 20

ema_decay: 0.995
