defaults:
  - _self_
  - noise_model: pakt_decoder_only
  - noise_distribution: loglogistic
  - noise_schedule: exponential
  - sampler: ddim
  - optimizer: adamw
  - lr_scheduler: warmup_cosine
  - goal_encoder: null

_target_: agents.pakt_beso_agent.BesoAgent

# Arguments passed at runtime:
# specs: ???
precondition_type: edm
obs_encoder:
  embed_dim: 512

qk_norm_weight_decay: 0.01           # <-- new; null disables the qk-norm group
exclude_norms_from_weight_decay: true # <-- new


# diffusion params
num_sampling_steps: 10
sigma_data: 0.5
sigma_min: 0.01
sigma_max: 80

ema_decay: 0.995
