# @package _global_

# overfits on a single trajectory, allowing for testing of the learning algorithm itself

defaults:
  - verbose

# overwrite task name so debugging logs are stored in separate folder
job_type: overfit

data:
  dataset:
    load_subset: [38]  # load selected trajectory
  preprocess:
    overwrite: True  # don't worry about overwriting the preprocessed data since we are using a small subset

trainer:
  log_every_n_steps: 1  # since epochs are short, we need to log after every batch
  max_epochs: 500
  check_val_every_n_epoch: 50

# create checkpoints less frequently since we're training for longer
callbacks:
  model_checkpoint:
    every_n_epochs: 50

# Set wandb notes to make it clear that this is an overfit run
logger:
  wandb:
    notes: overfit

# since we load a small subset of the data, store preprocessed data in another folder
paths:
  preprocessed_dir: ${paths.debug_preprocessed_dir}

platform:
  batch_size: 64  # reduce batch size to ensure we have at least 1 batch
