# @package _global_

defaults:
  - verbose

# overwrite task name so debugging logs are stored in separate folder
job_type: preprocess

# disable callbacks during debugging
callbacks: null

data:
  prepreprocess:
    overwrite: True
  preprocess:
    overwrite: True

trainer:
  max_epochs: 1
  fast_dev_run: true
