# @package _global_

defaults:
  - verbose

# overwrite task name so debugging logs are stored in separate folder
job_type: prepreprocessing

# disable callbacks and loggers during debugging
callbacks: null
logger: null

data:
  device: disk  # prevents trying to load trajectories after preprocessing
  dataset:
    backend: hdf5  # save back to disk as hdf5
    # overwrite_preprocessed: True
