# @package _global_

# uses only 10% of the training data

defaults:
  - verbose

# overwrite task name so debugging logs are stored in separate folder
job_type: "debug"

trainer:
  log_every_n_steps: 1  # since epochs are short, we need to log after every batch
  max_epochs: 5

data:
  dataset:
    load_subset: 0.05  # load only 5% of the training data

callbacks:
  model_checkpoint:
    every_n_epochs: 1  # save a checkpoint every epoch
