# @package _global_

# uses only 10% of the training data

defaults:
  - verbose

# overwrite task name so debugging logs are stored in separate folder
job_type: "debug"

trainer:
  log_every_n_steps: 1  # since epochs are short, we need to log after every batch
  max_epochs: 5

data:
  dataset:
    load_subset: 0.05  # load only 5% of the training data
    overwrite_preprocessed: True  # don't worry about overwriting the preprocessed data since we are using a small subset

callbacks:
  model_checkpoint:
    every_n_epochs: 1  # save a checkpoint every epoch

# since we load a small subset of the data, store preprocessed data in another folder
paths:
  preprocessed_dir: ${paths.debug_preprocessed_dir}
