# @package _global_

# runs 1 train, 1 validation and 1 test step

# overwrite task name so debugging logs are stored in separate folder
job_type: "debug"

# disable callbacks and loggers during debugging
callbacks: null
logger: null

# sets level of all command line loggers to 'DEBUG'
# https://hydra.cc/docs/tutorials/basic/running_your_app/logging/
hydra:
  verbose: True

trainer:
  max_epochs: 1
  accelerator: gpu  # run using gpu to test handling of device
  devices: 1 # debuggers don't like multiprocessing
  detect_anomaly: true # raise exception if NaN or +/-inf is detected in any tensor
  fast_dev_run: true

data:
  num_workers: 0  # debuggers don't like multiprocessing
  pin_memory: False  # disable gpu memory pin
  dataset:
    load_subset: 0.05  # load only 5% of the training data
