# @package _global_

# runs 1 train, 1 validation and 1 test step

defaults:
  - no_multiprocessing
  - verbose

# overwrite task name so debugging logs are stored in separate folder
job_type: debug

# disable callbacks and loggers during debugging
callbacks: null
logger: null

# # use this to also set hydra loggers to 'DEBUG'
# hydra:
#   verbose: True

python_logging:
  always_suppress_debug_from: null  # show debug logs from all modules

trainer:
  max_epochs: 1
  # # disabled `detect_anomaly` because it's not compatible with jagged tensor
  # detect_anomaly: true # raise exception if NaN or +/-inf is detected in any tensor
  fast_dev_run: true

data:
  dataset:
    load_subset: 1  # load only one trajectory
  preprocess:
    overwrite: True  # don't worry about overwriting the preprocessed data since we are using a small subset

# since we load a small subset of the data, store preprocessed data in another folder
paths:
  preprocessed_dir: ${paths.debug_preprocessed_dir}

platform:
  pin_memory: False  # disable gpu memory pin
  batch_size: 16  # reduce batch size to ensure we have at least 1 batch

torch:
  print_options:
    threshold: 10000  # print even large tensors without summarizing
