# @package _global_

# usage: python test.py -cn test_on_dataset debug=test_memorization

defaults:
  - verbose
  - override /callbacks: eval_trajectories

job_type: test_memorization

data:
  dataset:
    load_subset: [0]  # load selected trajectory
  preprocess:
    overwrite: True  # don't worry about overwriting the preprocessed data since we are using a small subset

# since we load a small subset of the data, store preprocessed data in another folder
paths:
  preprocessed_dir: ${paths.debug_preprocessed_dir}
