name: decoder_only
_target_: agents.backbones.decoder_only.DecoderOnlyNoise
_partial_: True

# Arguments defined in parent config:
decoder: ???
time_encoder: ???
sigma_encoder: ???
action_head: ???

# Arguments passed at runtime:
# dataset: ???
# obs_encoder: ???

token_dim: 256
dropout_prob: 0
