defaults:
  - backbone@decoder: new_transformer
  - time_encoder: learned
  - sigma_encoder: beso
  - action_head: linear
  - _self_

name: decoder_only
_target_: agents.backbones.decoder_only.DecoderOnlyNoise
_partial_: True

# Arguments passed at runtime:
# dataset: ???
# obs_encoder: ???

token_dim: 256
dropout_prob: 0
